// frameworks/qwik/src/hooks/useField/useField.ts
import {
  getElementInput,
  getFieldBool,
  getFieldInput,
  getFieldStore,
  INTERNAL,
  type RequiredPath,
  type Schema,
  setFieldBool,
  setFieldInput,
  validateIfRequired,
  type ValidPath,
} from '@formisch/core/qwik';
import {
  $,
  createComputed$,
  useComputed$,
  useConstant,
  useTask$,
} from '@qwik.dev/core';
import type * as v from 'valibot';
import type { FieldStore, FormStore } from '../../types/index.ts';
import { usePathSignal } from '../usePathSignal/index.ts';

export interface UseFieldConfig<
  TSchema extends Schema = Schema,
  TFieldPath extends RequiredPath = RequiredPath,
> {
  readonly path: ValidPath<v.InferInput<TSchema>, TFieldPath>;
}

export function useField<
  TSchema extends Schema,
  TFieldPath extends RequiredPath,
>(
  form: FormStore<TSchema>,
  config: UseFieldConfig<TSchema, TFieldPath>
): FieldStore<TSchema, TFieldPath>;
export function useField(form: FormStore, config: UseFieldConfig): FieldStore {
  const pathSignal = usePathSignal(config.path);
  const internalFieldStore = useComputed$(() =>
    getFieldStore(form[INTERNAL], pathSignal.value)
  );

  useTask$(({ track, cleanup }) => {
    track(internalFieldStore);
    cleanup(() => {
      internalFieldStore.value.elements =
        internalFieldStore.value.elements.filter(
          (element) => element.isConnected
        );
    });
  });

  return useConstant(() => ({
    path: pathSignal,
    input: createComputed$(() => getFieldInput(internalFieldStore.value)),
    errors: createComputed$(() => internalFieldStore.value.errors.value),
    isTouched: createComputed$(() =>
      getFieldBool(internalFieldStore.value, 'isTouched')
    ),
    isDirty: createComputed$(() =>
      getFieldBool(internalFieldStore.value, 'isDirty')
    ),
    isValid: createComputed$(
      () => !getFieldBool(internalFieldStore.value, 'errors')
    ),
    props: {
      get name() {
        return internalFieldStore.value.name;
      },
      autofocus: !!internalFieldStore.value.errors.value,
      ref: $((element) => {
        internalFieldStore.value.elements.push(element);
      }),
      onFocus$: $(() => {
        setFieldBool(internalFieldStore.value, 'isTouched', true);
        validateIfRequired(form[INTERNAL], internalFieldStore.value, 'touch');
      }),
      onInput$: $((_, element) => {
        const nextValue = getElementInput(element, internalFieldStore.value);
        setFieldInput(internalFieldStore.value, nextValue);
        validateIfRequired(form[INTERNAL], internalFieldStore.value, 'input');
      }),
      onChange$: $(() => {
        validateIfRequired(form[INTERNAL], internalFieldStore.value, 'change');
      }),
      onBlur$: $(() => {
        validateIfRequired(form[INTERNAL], internalFieldStore.value, 'blur');
      }),
    },
  }));
}

// frameworks/solid/src/primitives/useField/useField.ts
import {
  getElementInput,
  getFieldBool,
  getFieldInput,
  getFieldStore,
  INTERNAL,
  type RequiredPath,
  type Schema,
  setFieldBool,
  setFieldInput,
  validateIfRequired,
  type ValidPath,
} from '@formisch/core/solid';
import { createMemo, onCleanup } from 'solid-js';
import type * as v from 'valibot';
import type { FieldStore, FormStore, MaybeGetter } from '../../types/index.ts';
import { unwrap } from '../../utils/index.ts';

export interface UseFieldConfig<
  TSchema extends Schema = Schema,
  TFieldPath extends RequiredPath = RequiredPath,
> {
  readonly path: ValidPath<v.InferInput<TSchema>, TFieldPath>;
}

export function useField<
  TSchema extends Schema,
  TFieldPath extends RequiredPath,
>(
  form: MaybeGetter<FormStore<TSchema>>,
  config: MaybeGetter<UseFieldConfig<TSchema, TFieldPath>>
): FieldStore<TSchema, TFieldPath>;
export function useField(
  form: MaybeGetter<FormStore>,
  config: MaybeGetter<UseFieldConfig>
): FieldStore {
  const getInternalFormStore = createMemo(() => unwrap(form)[INTERNAL]);
  const getInternalFieldStore = createMemo(() =>
    getFieldStore(getInternalFormStore(), unwrap(config).path)
  );

  return {
    get path() {
      return unwrap(config).path;
    },
    get input() {
      return getFieldInput(getInternalFieldStore());
    },
    get errors() {
      return getInternalFieldStore().errors.value;
    },
    get isTouched() {
      return getFieldBool(getInternalFieldStore(), 'isTouched');
    },
    get isDirty() {
      return getFieldBool(getInternalFieldStore(), 'isDirty');
    },
    get isValid() {
      return !getFieldBool(getInternalFieldStore(), 'errors');
    },
    props: {
      get name() {
        return getInternalFieldStore().name;
      },
      // eslint-disable-next-line solid/reactivity
      autofocus: !!getInternalFieldStore().errors.value,
      ref: (element) => {
        const internalFieldStore = getInternalFieldStore();
        internalFieldStore.elements.push(element);
        onCleanup(() => {
          internalFieldStore.elements = internalFieldStore.elements.filter(
            (el) => el !== element
          );
        });
      },
      onFocus() {
        setFieldBool(getInternalFieldStore(), 'isTouched', true);
        validateIfRequired(
          getInternalFormStore(),
          getInternalFieldStore(),
          'touch'
        );
      },
      onInput(event) {
        const internalFieldStore = getInternalFieldStore();
        const nextValue = getElementInput(
          event.currentTarget,
          internalFieldStore
        );
        setFieldInput(internalFieldStore, nextValue);
        validateIfRequired(getInternalFormStore(), internalFieldStore, 'input');
      },
      onChange() {
        validateIfRequired(
          getInternalFormStore(),
          getInternalFieldStore(),
          'change'
        );
      },
      onBlur() {
        validateIfRequired(
          getInternalFormStore(),
          getInternalFieldStore(),
          'blur'
        );
      },
    },
  };
}
