// playgrounds/solid/src/components/UnstyledButton.tsx
import { A } from '@solidjs/router';
import clsx from 'clsx';
import { createSignal, type JSX, Match, Switch } from 'solid-js';
import { Spinner } from './Spinner';

type LinkProps = {
  type: 'link';
  href: string;
  download?: boolean | string;
  target?: '_blank';
};

type ButtonProps = {
  type: 'button' | 'reset' | 'submit';
  onClick?: () => unknown;
  loading?: boolean;
  form?: string;
};

export type DefaultButtonProps = LinkProps | ButtonProps;

type UnstyledButtonProps = DefaultButtonProps & {
  class?: string;
  children: JSX.Element;
  'aria-label'?: string;
};

/**
 * Basic button component that contains important functionality and is used to
 * build more complex components on top of it.
 */
export function UnstyledButton(props: UnstyledButtonProps) {
  // Use loading signal
  const [getLoading, setLoading] = createSignal(false);

  return (
    <Switch>
      {/* Link button */}
      <Match when={props.type === 'link' && props} keyed>
        {(link) => (
          <A
            {...link}
            rel={link.target === '_blank' ? 'noreferrer' : undefined}
          >
            {link.children}
          </A>
        )}
      </Match>

      {/* Normal button */}
      <Match when={props.type !== 'link' && props} keyed>
        {(button) => (
          <button
            {...button}
            disabled={getLoading() || button.loading}
            // Start and stop loading if function is async
            onClick={
              button.onClick &&
              (async () => {
                setLoading(true);
                await button.onClick!();
                setLoading(false);
              })
            }
          >
            <span
              class={clsx(
                'transition-[opacity,transform,visibility] duration-200',
                getLoading() || button.loading
                  ? 'invisible translate-x-5 opacity-0'
                  : 'visible delay-300'
              )}
            >
              {button.children}
            </span>
            <span
              class={clsx(
                'absolute duration-200',
                getLoading() || button.loading
                  ? 'visible delay-300'
                  : 'invisible -translate-x-5 opacity-0'
              )}
            >
              <Spinner />
            </span>
          </button>
        )}
      </Match>
    </Switch>
  );
}

// playgrounds/qwik/src/components/UnstyledButton.tsx
import { $, component$, Slot, useSignal } from '@qwik.dev/core';
import { Link } from '@qwik.dev/router';
import clsx from 'clsx';
import { Spinner } from './Spinner';

type LinkProps = {
  type: 'link';
  href: string;
  download?: boolean | string;
  target?: '_blank';
};

type ButtonProps = {
  type: 'button' | 'reset' | 'submit';
  'preventdefault:click'?: boolean;
  onClick$?: () => unknown;
  loading?: boolean;
  form?: string;
};

export type DefaultButtonProps = LinkProps | ButtonProps;

type UnstyledButtonProps = DefaultButtonProps & {
  class?: string;
  'aria-label'?: string;
};

/**
 * Basic button component that contains important functionality and is used to
 * build more complex components on top of it.
 */
export const UnstyledButton = component$((props: UnstyledButtonProps) => {
  // Use loading signal
  const loading = useSignal(false);

  return (
    <>
      {/* Link button */}
      {props.type === 'link' && (
        <Link
          {...props}
          rel={props.target === '_blank' ? 'noreferrer' : undefined}
        >
          <Slot />
        </Link>
      )}

      {/* Normal button */}
      {props.type !== 'link' && (
        <button
          {...props}
          disabled={loading.value || props.loading}
          // Start and stop loading if function is async
          onClick$={
            props.onClick$ &&
            $(async () => {
              loading.value = true;
              await props.onClick$!();
              loading.value = false;
            })
          }
        >
          <span
            class={clsx(
              'transition-[opacity,transform,visibility] duration-200',
              loading.value || props.loading
                ? 'invisible translate-x-5 opacity-0'
                : 'visible delay-300'
            )}
          >
            <Slot />
          </span>
          <span
            class={clsx(
              'absolute duration-200',
              loading.value || props.loading
                ? 'visible delay-300'
                : 'invisible -translate-x-5 opacity-0'
            )}
          >
            <Spinner />
          </span>
        </button>
      )}
    </>
  );
});
