// website/src/components/FormHeader.tsx
import { type FormStore, reset } from '@formisch/qwik';
import { component$ } from '@qwik.dev/core';
import { ActionButton } from './ActionButton';

type FormHeaderProps = {
  of: FormStore;
  heading: string;
};

/**
 * Form header with heading and buttons to reset and submit the form.
 */
export const FormHeader = component$(
  ({ of: form, heading }: FormHeaderProps) => {
    return (
      <header class="flex items-center justify-between px-8 lg:px-10">
        <h1 class="text-2xl text-slate-900 md:text-3xl lg:text-4xl dark:text-slate-200">
          {heading}
        </h1>
        <div class="hidden lg:flex lg:gap-8">
          <ActionButton
            variant="secondary"
            label="Reset"
            type="button"
            preventdefault:click
            onClick$={() => reset(form)}
          />
          <ActionButton variant="primary" label="Submit" type="submit" />
        </div>
      </header>
    );
  }
);

// playgrounds/vue/src/components/FormHeader.vue
<script setup lang="ts">
import { type FormStore, reset } from '@formisch/vue';
import ActionButton from './ActionButton.vue';

type FormHeaderProps = {
  of: FormStore;
  heading: string;
};

const props = defineProps<FormHeaderProps>();

const handleReset = () => {
  reset(props.of);
};
</script>

<template>
  <header class="flex items-center justify-between px-8 lg:px-10">
    <h1
      class="text-2xl text-slate-900 md:text-3xl lg:text-4xl dark:text-slate-200"
    >
      {{ props.heading }}
    </h1>
    <div class="hidden lg:flex lg:space-x-8">
      <ActionButton
        variant="secondary"
        label="Reset"
        type="button"
        @click="handleReset"
      />
      <ActionButton variant="primary" label="Submit" type="submit" />
    </div>
  </header>
</template>
