// playgrounds/svelte/src/lib/components/InputLabel.svelte
<script lang="ts">
  interface Props {
    name?: string;
    label?: string;
    required?: boolean;
    margin?: 'none';
  }

  let { name, label, required, margin }: Props = $props();
</script>

{#if label}
  {#if name}
    <label
      class={[
        'inline-block font-medium md:text-lg lg:text-xl',
        {
          'mb-4 lg:mb-5': !margin,
        },
      ]}
      for={name}
    >
      {label}
      {#if required}
        <span class="ml-1 text-red-600 dark:text-red-400">*</span>
      {/if}
    </label>
  {:else}
    <div
      class={[
        'inline-block font-medium md:text-lg lg:text-xl',
        {
          'mb-4 lg:mb-5': !margin,
        },
      ]}
    >
      {label}
      {#if required}
        <span class="ml-1 text-red-600 dark:text-red-400">*</span>
      {/if}
    </div>
  {/if}
{/if}

// playgrounds/vue/src/components/InputLabel.vue
<script setup lang="ts">
type InputLabelProps = {
  name?: string;
  label?: string;
  required?: boolean;
  margin?: 'none';
};

defineProps<InputLabelProps>();
</script>

<template>
  <component
    v-if="label"
    :is="name ? 'label' : 'div'"
    :class="[
      'inline-block font-medium md:text-lg lg:text-xl',
      { 'mb-4 lg:mb-5': !margin },
    ]"
    :for="name"
  >
    {{ label }}
    <span v-if="required" class="ml-1 text-red-600 dark:text-red-400">*</span>
  </component>
</template>
