// playgrounds/qwik/src/components/ButtonGroup.tsx
import { component$, Slot } from '@qwik.dev/core';
import clsx from 'clsx';

type ButtonGroupProps = {
  class?: string;
};

/**
 * Button group displays multiple related actions side-by-side and helps with
 * arrangement and spacing.
 */
export const ButtonGroup = component$((props: ButtonGroupProps) => (
  <div class={clsx('flex flex-wrap gap-6 px-8 lg:gap-8 lg:px-10', props.class)}>
    <Slot />
  </div>
));

// playgrounds/preact/src/components/ButtonGroup.tsx
import clsx from 'clsx';
import { ComponentChildren } from 'preact';

type ButtonGroupProps = {
  class?: string;
  children: ComponentChildren;
};

/**
 * Button group displays multiple related actions side-by-side and helps with
 * arrangement and spacing.
 */
export function ButtonGroup({ children, ...props }: ButtonGroupProps) {
  return (
    <div
      class={clsx('flex flex-wrap gap-6 px-8 lg:gap-8 lg:px-10', props.class)}
    >
      {children}
    </div>
  );
}
